name = "gemini2api"
main = "worker.js"
compatibility_date = "2024-12-01"
keep_vars = true

[triggers]
crons = ["*/10 * * * *"]

[[durable_objects.bindings]]
name = "COOKIE_STORE"
class_name = "CookieStore"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CookieStore"]
